---
repos:
  - repo: https://github.com/PyCQA/doc8
    rev: 0.10.1
    hooks:
      - id: doc8
        name: doc8
        description: This hook runs doc8 for linting docs.
        entry: python -m doc8
        language: python
        files: \.rst$
        require_serial: true
  - repo: https://github.com/psf/black.git
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(tests\/hooks-abort-render\/hooks|docs\/HelloCookieCutter1)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-absolute-import
          - flake8-black
          - flake8-docstrings
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--ini, .bandit]
